-- ================================================================
-- SUPABASE DATABASE SCHEMA FOR RCD (Report of Collections & Deposits)
-- Role-Based Access: 'user' (Collector) & 'admin' (Administrator)
-- Admin can monitor all collections, reports, and users
-- ================================================================

-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 2. USER PROFILES TABLE (rcd_profiles)
create table if not exists public.rcd_profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text not null,
  full_name text,
  role text default 'user' not null, -- 'user' (Collector) or 'admin' (Administrator)
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Helper function to check if current user is an Admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.rcd_profiles
    where id = auth.uid() and lower(role) in ('admin', 'administrator')
  );
end;
$$ language plpgsql security definer;

-- Trigger to automatically create a profile when a new user signs up in Supabase Auth
create or replace function public.handle_new_rcd_user()
returns trigger as $$
begin
  insert into public.rcd_profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'user')
  )
  on conflict (id) do update
  set 
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.rcd_profiles.full_name),
    role = coalesce(excluded.role, public.rcd_profiles.role),
    updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists and recreate
drop trigger if exists on_auth_user_created_rcd on auth.users;
create trigger on_auth_user_created_rcd
  after insert on auth.users
  for each row execute procedure public.handle_new_rcd_user();

-- 3. RCD REPORTS TABLE (rcd_reports)
create table if not exists public.rcd_reports (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid() not null,
  report_number text not null,
  date date not null default current_date,
  collector_name text not null,
  fund_type text not null check (fund_type in ('General Fund', 'Trust Fund', 'SEF')),
  collections jsonb not null default '[]'::jsonb,
  total_collection numeric(14, 2) not null default 0,
  deposits jsonb not null default '[]'::jsonb,
  total_deposit numeric(14, 2) not null default 0,
  status text not null default 'Draft' check (status in ('Draft', 'Submitted', 'Verified')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_rcd_reports_user_id on public.rcd_reports(user_id);
create index if not exists idx_rcd_reports_date on public.rcd_reports(date);

-- 4. GENERAL COLLECTIONS TABLE (rcd_collections)
create table if not exists public.rcd_collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid() not null,
  af_no text,
  or_no text,
  payor text,
  sub_category text,
  main_category text,
  account_code text,
  amount numeric(14, 2) not null default 0,
  date date default current_date,
  remarks text,
  created_at timestamptz default now()
);

create index if not exists idx_rcd_collections_user_id on public.rcd_collections(user_id);
create index if not exists idx_rcd_collections_date on public.rcd_collections(date);

-- 5. REAL PROPERTY TAX (RPT) COLLECTIONS TABLE (rcd_rpt_collections)
create table if not exists public.rcd_rpt_collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid() not null,
  af56_id text,
  or_number text,
  payor text,
  barangay text,
  land_name text,
  td_number text,
  years_paid text,
  amount numeric(14, 2) not null default 0,
  date date default current_date,
  remarks text,
  created_at timestamptz default now()
);

create index if not exists idx_rcd_rpt_collections_user_id on public.rcd_rpt_collections(user_id);
create index if not exists idx_rcd_rpt_collections_date on public.rcd_rpt_collections(date);

-- 6. ACCOUNT CODES TABLE (rcd_account_codes)
create table if not exists public.rcd_account_codes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  main_category text not null,
  sub_category text not null,
  code text not null,
  created_at timestamptz default now()
);

create index if not exists idx_rcd_account_codes_user_id on public.rcd_account_codes(user_id);

-- 7. SIGNATORIES TABLE (rcd_signatories)
create table if not exists public.rcd_signatories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  full_name text not null,
  position text not null,
  department text not null,
  remarks text,
  created_at timestamptz default now()
);

create index if not exists idx_rcd_signatories_user_id on public.rcd_signatories(user_id);

-- ================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Regular 'user' sees/modifies only their own data.
-- 'admin' can view and monitor all collections and reports.
-- ================================================================

-- Enable RLS on all tables
alter table public.rcd_profiles enable row level security;
alter table public.rcd_reports enable row level security;
alter table public.rcd_collections enable row level security;
alter table public.rcd_rpt_collections enable row level security;
alter table public.rcd_account_codes enable row level security;
alter table public.rcd_signatories enable row level security;

-- 1. PROFILES POLICIES (rcd_profiles)
-- Users see their own profile, Admins see and manage all profiles (CRUD)
drop policy if exists "Users and Admins view profiles" on public.rcd_profiles;
drop policy if exists "Users can view profiles" on public.rcd_profiles;
drop policy if exists "Users can view their own profile" on public.rcd_profiles;
create policy "Users and Admins view profiles"
  on public.rcd_profiles for select
  using (auth.uid() = id or public.is_admin());

drop policy if exists "Users and Admins insert profiles" on public.rcd_profiles;
create policy "Users and Admins insert profiles"
  on public.rcd_profiles for insert
  with check (auth.uid() = id or public.is_admin());

drop policy if exists "Users and Admins update profiles" on public.rcd_profiles;
drop policy if exists "Users can update profiles" on public.rcd_profiles;
drop policy if exists "Users can update their own profile" on public.rcd_profiles;
create policy "Users and Admins update profiles"
  on public.rcd_profiles for update
  using (auth.uid() = id or public.is_admin());

drop policy if exists "Admins can delete profiles" on public.rcd_profiles;
drop policy if exists "Users and Admins delete profiles" on public.rcd_profiles;
create policy "Admins can delete profiles"
  on public.rcd_profiles for delete
  using (public.is_admin());

-- 2. RCD REPORTS POLICIES (rcd_reports)
-- Users view own reports, Admins view ALL reports
drop policy if exists "Users and Admins view reports" on public.rcd_reports;
drop policy if exists "Users can view reports" on public.rcd_reports;
drop policy if exists "Users can view their own reports" on public.rcd_reports;
create policy "Users and Admins view reports"
  on public.rcd_reports for select
  using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users and Admins insert reports" on public.rcd_reports;
drop policy if exists "Users can insert reports" on public.rcd_reports;
drop policy if exists "Users can insert their own reports" on public.rcd_reports;
create policy "Users and Admins insert reports"
  on public.rcd_reports for insert
  with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users and Admins update reports" on public.rcd_reports;
drop policy if exists "Users can update reports" on public.rcd_reports;
drop policy if exists "Users can update their own reports" on public.rcd_reports;
create policy "Users and Admins update reports"
  on public.rcd_reports for update
  using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users and Admins delete reports" on public.rcd_reports;
drop policy if exists "Users can delete reports" on public.rcd_reports;
drop policy if exists "Users can delete their own reports" on public.rcd_reports;
create policy "Users and Admins delete reports"
  on public.rcd_reports for delete
  using (auth.uid() = user_id or public.is_admin());

-- 3. COLLECTIONS POLICIES (rcd_collections)
-- Collectors create, edit and delete their own collections.
-- Admins can ONLY view and consolidate (Admin cannot modify or delete collector entries).
drop policy if exists "Users and Admins view collections" on public.rcd_collections;
drop policy if exists "Users can view collections" on public.rcd_collections;
drop policy if exists "Users can view their own collections" on public.rcd_collections;
create policy "Users and Admins view collections"
  on public.rcd_collections for select
  using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users and Admins insert collections" on public.rcd_collections;
drop policy if exists "Users can insert collections" on public.rcd_collections;
drop policy if exists "Users can insert their own collections" on public.rcd_collections;
create policy "Users and Admins insert collections"
  on public.rcd_collections for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users and Admins update collections" on public.rcd_collections;
drop policy if exists "Users can update collections" on public.rcd_collections;
drop policy if exists "Users can update their own collections" on public.rcd_collections;
create policy "Users and Admins update collections"
  on public.rcd_collections for update
  using (auth.uid() = user_id);

drop policy if exists "Users and Admins delete collections" on public.rcd_collections;
drop policy if exists "Users can delete collections" on public.rcd_collections;
drop policy if exists "Users can delete their own collections" on public.rcd_collections;
create policy "Users and Admins delete collections"
  on public.rcd_collections for delete
  using (auth.uid() = user_id);

-- 4. RPT COLLECTIONS POLICIES (rcd_rpt_collections)
-- Collectors create, edit and delete their own RPT collections.
-- Admins can ONLY view and consolidate (Admin cannot modify or delete collector entries).
drop policy if exists "Users and Admins view rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can view rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can view their own RPT collections" on public.rcd_rpt_collections;
create policy "Users and Admins view rpt collections"
  on public.rcd_rpt_collections for select
  using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users and Admins insert rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can insert rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can insert their own RPT collections" on public.rcd_rpt_collections;
create policy "Users and Admins insert rpt collections"
  on public.rcd_rpt_collections for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users and Admins update rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can update rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can update their own RPT collections" on public.rcd_rpt_collections;
create policy "Users and Admins update rpt collections"
  on public.rcd_rpt_collections for update
  using (auth.uid() = user_id);

drop policy if exists "Users and Admins delete rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can delete rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can delete their own RPT collections" on public.rcd_rpt_collections;
create policy "Users and Admins delete rpt collections"
  on public.rcd_rpt_collections for delete
  using (auth.uid() = user_id);

-- 5. ACCOUNT CODES POLICIES (rcd_account_codes)
-- All users share the exact same source of account codes; Admins manage codes globally
drop policy if exists "Users and Admins view account codes" on public.rcd_account_codes;
drop policy if exists "Users can view account codes" on public.rcd_account_codes;
create policy "Users and Admins view account codes"
  on public.rcd_account_codes for select
  using (true);

drop policy if exists "Users and Admins insert account codes" on public.rcd_account_codes;
drop policy if exists "Users can insert account codes" on public.rcd_account_codes;
create policy "Admins insert account codes"
  on public.rcd_account_codes for insert
  with check (public.is_admin());

drop policy if exists "Users and Admins update account codes" on public.rcd_account_codes;
drop policy if exists "Users can update account codes" on public.rcd_account_codes;
drop policy if exists "Users can update their own account codes" on public.rcd_account_codes;
create policy "Admins update account codes"
  on public.rcd_account_codes for update
  using (public.is_admin());

drop policy if exists "Users and Admins delete account codes" on public.rcd_account_codes;
drop policy if exists "Users can delete account codes" on public.rcd_account_codes;
drop policy if exists "Users can delete their own account codes" on public.rcd_account_codes;
create policy "Admins delete account codes"
  on public.rcd_account_codes for delete
  using (public.is_admin());

-- 6. SIGNATORIES POLICIES (rcd_signatories)
-- All users view global officials and their own certification signatory;
-- Collectors can edit their own Certification signature; Admins manage global officials.
drop policy if exists "Users and Admins view signatories" on public.rcd_signatories;
drop policy if exists "Users can view signatories" on public.rcd_signatories;
create policy "Users and Admins view signatories"
  on public.rcd_signatories for select
  using (auth.uid() = user_id or user_id is null or public.is_admin());

drop policy if exists "Users and Admins insert signatories" on public.rcd_signatories;
drop policy if exists "Users can insert signatories" on public.rcd_signatories;
create policy "Users and Admins insert signatories"
  on public.rcd_signatories for insert
  with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users and Admins update signatories" on public.rcd_signatories;
drop policy if exists "Users can update signatories" on public.rcd_signatories;
drop policy if exists "Users can update their own signatories" on public.rcd_signatories;
create policy "Users and Admins update signatories"
  on public.rcd_signatories for update
  using (auth.uid() = user_id or (user_id is null and public.is_admin()) or public.is_admin());

drop policy if exists "Users and Admins delete signatories" on public.rcd_signatories;
drop policy if exists "Users can delete signatories" on public.rcd_signatories;
drop policy if exists "Users can delete their own signatories" on public.rcd_signatories;
create policy "Users and Admins delete signatories"
  on public.rcd_signatories for delete
  using (auth.uid() = user_id or public.is_admin());

-- ================================================================
-- INITIAL SEED DATA (System default account codes & signatories)
-- ================================================================
insert into public.rcd_account_codes (user_id, main_category, sub_category, code) values
  (null, 'Tax Revenue', 'Community Tax - Individual', '4-01-01-050'),
  (null, 'Tax Revenue', 'Community Tax - Corporation', '4-01-01-060'),
  (null, 'Tax Revenue', 'Real Property Tax - Basic', '4-01-02-040'),
  (null, 'Tax Revenue', 'Special Education Tax (SEF)', '4-01-02-050'),
  (null, 'Tax Revenue', 'Business Tax', '4-01-03-010'),
  (null, 'Service and Business Income', 'Permit Fees (Mayor''s Permit)', '4-02-01-010'),
  (null, 'Service and Business Income', 'Clearance and Certification Fees', '4-02-01-040'),
  (null, 'Service and Business Income', 'Garbage Fees', '4-02-01-100'),
  (null, 'Service and Business Income', 'Market Operations', '4-02-02-050'),
  (null, 'Service and Business Income', 'Slaughterhouse Operations', '4-02-02-060'),
  (null, 'Service and Business Income', 'Cemetery Operations', '4-02-02-070')
on conflict do nothing;

insert into public.rcd_signatories (user_id, full_name, position, department, remarks) values
  (null, 'MENARD A. HERRERA', 'Revenue Collection Clerk II', 'Office of the Municipal Treasurer', 'Treasurer''s Office Staff / Certification'),
  (null, 'MARIA SANTOS, CPA', 'Municipal Treasurer', 'Office of the Municipal Treasurer', 'Municipal Treasurer / Verification & Acknowledgment'),
  (null, 'HESTHER F. FANOGA', 'AA II', 'Office of the Municipal Accountant', 'Accounting Staff / Prepared by'),
  (null, 'PEDRO REYES', 'Municipal Accountant', 'Office of the Municipal Accountant', 'Municipal Accountant / Certified Correct')
on conflict do nothing;
