-- ================================================================
-- SUPABASE DATABASE SCHEMA FOR RCD (Report of Collections & Deposits)
-- Role-Based Access: 'user' (Collector) & 'admin' (Administrator)
-- Custom Table Authentication using public.users table
-- ================================================================

-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 2. USERS & AUTHENTICATION TABLE (public.users)
create table if not exists public.users (
  userid uuid default gen_random_uuid() not null,
  firstname text not null,
  lastname text not null,
  password text not null,
  department text null,
  position text null,
  role text null default 'user', -- 'admin' or 'user'
  email text null,
  status text null default 'Active', -- 'Active' or 'Inactive'
  datecreated timestamp with time zone null default now(),
  lastlogin timestamp with time zone null,
  signature text null,
  signature_url text null,
  constraint users_pkey primary key (userid),
  constraint users_email_key unique (email)
);

-- Disable Row Level Security on public.users for direct application authentication & management
alter table public.users disable row level security;
grant all on table public.users to anon, authenticated, service_role;

-- 3. RCD REPORTS TABLE (rcd_reports)
create table if not exists public.rcd_reports (
  id uuid default gen_random_uuid() primary key,
  user_id uuid null,
  collector_email text null,
  report_number text not null,
  date date not null default current_date,
  collector_name text not null,
  fund_type text not null check (fund_type in ('General Fund', 'Trust Fund', 'SEF')),
  collections jsonb not null default '[]'::jsonb,
  total_collection numeric(14, 2) not null default 0,
  deposits jsonb not null default '[]'::jsonb,
  total_deposit numeric(14, 2) not null default 0,
  status text not null default 'Draft' check (status in ('Draft', 'Submitted', 'Verified')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.rcd_reports add column if not exists collector_email text;
create index if not exists idx_rcd_reports_user_id on public.rcd_reports(user_id);
create index if not exists idx_rcd_reports_collector_email on public.rcd_reports(collector_email);
create index if not exists idx_rcd_reports_date on public.rcd_reports(date);

-- 4. GENERAL COLLECTIONS TABLE (rcd_collections)
create table if not exists public.rcd_collections (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  collector_email text null,
  af_no text,
  or_no text,
  payor text,
  sub_category text,
  main_category text,
  account_code text,
  amount numeric(14, 2) not null default 0,
  date date default current_date,
  remarks text,
  created_at timestamptz default now()
);

alter table public.rcd_collections add column if not exists collector_email text;
alter table public.rcd_collections add column if not exists status text default 'Pending';
create index if not exists idx_rcd_collections_user_id on public.rcd_collections(user_id);
create index if not exists idx_rcd_collections_collector_email on public.rcd_collections(collector_email);
create index if not exists idx_rcd_collections_date on public.rcd_collections(date);
create index if not exists idx_rcd_collections_status on public.rcd_collections(status);

-- 5. REAL PROPERTY TAX (RPT) COLLECTIONS TABLE (rcd_rpt_collections)
create table if not exists public.rcd_rpt_collections (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  collector_email text null,
  af56_id text,
  or_number text,
  payor text,
  barangay text,
  land_name text,
  td_number text,
  years_paid text,
  amount numeric(14, 2) not null default 0,
  date date default current_date,
  remarks text,
  created_at timestamptz default now()
);

alter table public.rcd_rpt_collections add column if not exists collector_email text;
alter table public.rcd_rpt_collections add column if not exists status text default 'Pending';
create index if not exists idx_rcd_rpt_collections_user_id on public.rcd_rpt_collections(user_id);
create index if not exists idx_rcd_rpt_collections_collector_email on public.rcd_rpt_collections(collector_email);
create index if not exists idx_rcd_rpt_collections_date on public.rcd_rpt_collections(date);
create index if not exists idx_rcd_rpt_collections_status on public.rcd_rpt_collections(status);

-- 6. ACCOUNT CODES TABLE (rcd_account_codes)
create table if not exists public.rcd_account_codes (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  main_category text not null,
  sub_category text not null,
  code text not null,
  created_at timestamptz default now()
);

create index if not exists idx_rcd_account_codes_user_id on public.rcd_account_codes(user_id);

-- 7. SIGNATORIES TABLE (rcd_signatories)
create table if not exists public.rcd_signatories (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  full_name text not null,
  position text not null,
  department text not null,
  remarks text,
  created_at timestamptz default now()
);

create index if not exists idx_rcd_signatories_user_id on public.rcd_signatories(user_id);

-- 8. LGU DEPARTMENTS TABLE (lgu_departments)
create table if not exists public.lgu_departments (
  id uuid not null default gen_random_uuid (),
  department_code character varying(50) not null,
  department_name character varying(255) not null,
  department_acronym character varying(50) null,
  description text null,
  department_head character varying(255) null,
  contact_number character varying(50) null,
  email character varying(255) null,
  office_location character varying(255) null,
  parent_department_id uuid null,
  is_active boolean null default true,
  created_by uuid null,
  created_by_name character varying(255) null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp with time zone null default CURRENT_TIMESTAMP,
  logo_url text null,
  constraint lgu_departments_pkey primary key (id),
  constraint lgu_departments_department_code_key unique (department_code),
  constraint lgu_departments_parent_department_id_fkey foreign KEY (parent_department_id) references lgu_departments (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_department_code on public.lgu_departments using btree (department_code) TABLESPACE pg_default;
create index IF not exists idx_department_name on public.lgu_departments using btree (department_name) TABLESPACE pg_default;
create index IF not exists idx_parent_department on public.lgu_departments using btree (parent_department_id) TABLESPACE pg_default;
create index IF not exists idx_is_active on public.lgu_departments using btree (is_active) TABLESPACE pg_default;

alter table public.lgu_departments disable row level security;

-- ================================================================
-- DISABLE ROW LEVEL SECURITY (RLS) & REMOVE OLD CONSTRAINTS
-- ================================================================

-- Drop foreign key constraints linking to auth.users
alter table if exists public.rcd_collections drop constraint if exists rcd_collections_user_id_fkey;
alter table if exists public.rcd_rpt_collections drop constraint if exists rcd_rpt_collections_user_id_fkey;
alter table if exists public.rcd_reports drop constraint if exists rcd_reports_user_id_fkey;
alter table if exists public.rcd_account_codes drop constraint if exists rcd_account_codes_user_id_fkey;
alter table if exists public.rcd_signatories drop constraint if exists rcd_signatories_user_id_fkey;

alter table if exists public.rcd_collections alter column user_id drop not null;
alter table if exists public.rcd_rpt_collections alter column user_id drop not null;
alter table if exists public.rcd_reports alter column user_id drop not null;

-- Disable Row Level Security (RLS) across all tables
alter table if exists public.users disable row level security;
alter table if exists public.rcd_collections disable row level security;
alter table if exists public.rcd_rpt_collections disable row level security;
alter table if exists public.rcd_reports disable row level security;
alter table if exists public.rcd_account_codes disable row level security;
alter table if exists public.rcd_signatories disable row level security;
alter table if exists public.rcd_profiles disable row level security;

-- Drop obsolete auth.uid() policies if any exist
drop policy if exists "Users and Admins view collections" on public.rcd_collections;
drop policy if exists "Users can view collections" on public.rcd_collections;
drop policy if exists "Users can view their own collections" on public.rcd_collections;
drop policy if exists "Users and Admins insert collections" on public.rcd_collections;
drop policy if exists "Users can insert collections" on public.rcd_collections;
drop policy if exists "Users can insert their own collections" on public.rcd_collections;
drop policy if exists "Users and Admins update collections" on public.rcd_collections;
drop policy if exists "Users can update collections" on public.rcd_collections;
drop policy if exists "Users can update their own collections" on public.rcd_collections;
drop policy if exists "Users and Admins delete collections" on public.rcd_collections;
drop policy if exists "Users can delete collections" on public.rcd_collections;
drop policy if exists "Users can delete their own collections" on public.rcd_collections;

drop policy if exists "Users and Admins view rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can view rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can view their own RPT collections" on public.rcd_rpt_collections;
drop policy if exists "Users and Admins insert rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can insert rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can insert their own RPT collections" on public.rcd_rpt_collections;
drop policy if exists "Users and Admins update rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can update rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can update their own RPT collections" on public.rcd_rpt_collections;
drop policy if exists "Users and Admins delete rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can delete rpt collections" on public.rcd_rpt_collections;
drop policy if exists "Users can delete their own RPT collections" on public.rcd_rpt_collections;

drop policy if exists "Users and Admins view reports" on public.rcd_reports;
drop policy if exists "Users can view reports" on public.rcd_reports;
drop policy if exists "Users can view their own reports" on public.rcd_reports;
drop policy if exists "Users and Admins insert reports" on public.rcd_reports;
drop policy if exists "Users can insert reports" on public.rcd_reports;
drop policy if exists "Users can insert their own reports" on public.rcd_reports;
drop policy if exists "Users and Admins update reports" on public.rcd_reports;
drop policy if exists "Users can update reports" on public.rcd_reports;
drop policy if exists "Users can update their own reports" on public.rcd_reports;
drop policy if exists "Users and Admins delete reports" on public.rcd_reports;
drop policy if exists "Users can delete reports" on public.rcd_reports;
drop policy if exists "Users can delete their own reports" on public.rcd_reports;

drop policy if exists "Users and Admins view account codes" on public.rcd_account_codes;
drop policy if exists "Users can view account codes" on public.rcd_account_codes;
drop policy if exists "Users and Admins insert account codes" on public.rcd_account_codes;
drop policy if exists "Users can insert account codes" on public.rcd_account_codes;
drop policy if exists "Admins insert account codes" on public.rcd_account_codes;
drop policy if exists "Users and Admins update account codes" on public.rcd_account_codes;
drop policy if exists "Users can update account codes" on public.rcd_account_codes;
drop policy if exists "Users can update their own account codes" on public.rcd_account_codes;
drop policy if exists "Admins update account codes" on public.rcd_account_codes;
drop policy if exists "Users and Admins delete account codes" on public.rcd_account_codes;
drop policy if exists "Users can delete account codes" on public.rcd_account_codes;
drop policy if exists "Users can delete their own account codes" on public.rcd_account_codes;
drop policy if exists "Admins delete account codes" on public.rcd_account_codes;

drop policy if exists "Users and Admins view signatories" on public.rcd_signatories;
drop policy if exists "Users can view signatories" on public.rcd_signatories;
drop policy if exists "Users and Admins insert signatories" on public.rcd_signatories;
drop policy if exists "Users can insert signatories" on public.rcd_signatories;
drop policy if exists "Users and Admins update signatories" on public.rcd_signatories;
drop policy if exists "Users can update signatories" on public.rcd_signatories;
drop policy if exists "Users can update their own signatories" on public.rcd_signatories;
drop policy if exists "Users and Admins delete signatories" on public.rcd_signatories;
drop policy if exists "Users can delete signatories" on public.rcd_signatories;
drop policy if exists "Users can delete their own signatories" on public.rcd_signatories;

-- Create open fallback policies in case RLS is enabled or re-enabled
drop policy if exists "open_access_collections" on public.rcd_collections;
create policy "open_access_collections" on public.rcd_collections for all to public using (true) with check (true);

drop policy if exists "open_access_rpt_collections" on public.rcd_rpt_collections;
create policy "open_access_rpt_collections" on public.rcd_rpt_collections for all to public using (true) with check (true);

drop policy if exists "open_access_reports" on public.rcd_reports;
create policy "open_access_reports" on public.rcd_reports for all to public using (true) with check (true);

drop policy if exists "open_access_account_codes" on public.rcd_account_codes;
create policy "open_access_account_codes" on public.rcd_account_codes for all to public using (true) with check (true);

drop policy if exists "open_access_signatories" on public.rcd_signatories;
create policy "open_access_signatories" on public.rcd_signatories for all to public using (true) with check (true);

drop policy if exists "open_access_users" on public.users;
create policy "open_access_users" on public.users for all to public using (true) with check (true);

-- Grant all permissions on all tables and sequences to anon, authenticated, service_role
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;

-- ================================================================
-- INITIAL SEED DATA (System default official signatories)
-- ================================================================
insert into public.rcd_signatories (user_id, full_name, position, department, remarks) values
  (null, 'MENARD A. HERRERA', 'Municipal Treasurer', 'Office of the Municipal Treasurer', 'Municipal Treasurer / Verification & Acknowledgment'),
  (null, 'LEON F. PAZ, JR.', 'Municipal Accountant', 'Office of the Municipal Accountant', 'Municipal Accountant / Certified Correct'),
  (null, 'HESTHER F. FANOGA', 'AA II', 'Office of the Municipal Accountant', 'Accounting Staff / Prepared by')
on conflict do nothing;
