import React, { useState, useEffect } from 'react';
import { 
  Box, 
  Typography, 
  Paper, 
  Table, 
  TableBody, 
  TableCell, 
  TableContainer, 
  TableHead, 
  TableRow, 
  Button, 
  IconButton, 
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Grid,
  CircularProgress,
  Backdrop,
  Autocomplete
} from '@mui/material';
import { Add, Edit, Delete, Refresh } from '@mui/icons-material';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { getAccountCodes, saveAccountCode, deleteAccountCode } from '../services/googleSheets';
import type { AccountCode } from '../types/rcd';

export const AccountCodesPage: React.FC = () => {
  const [accountCodes, setAccountCodes] = useState<AccountCode[]>([]);
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [currentId, setCurrentId] = useState<number | null>(null);

  // Delete Dialog State
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [itemToDelete, setItemToDelete] = useState<number | null>(null);

  // Form State
  const [formData, setFormData] = useState({
    mainCategory: '',
    subCategory: '',
    code: ''
  });

  // Derived state for unique main categories
  const uniqueMainCategories = Array.from(new Set(accountCodes.map(c => c.mainCategory))).filter(Boolean).sort();

  const getCommonPrefix = (category: string, codes: AccountCode[]) => {
    const categoryCodes = codes
      .filter(c => c.mainCategory === category)
      .map(c => c.code)
      .filter(Boolean);

    if (categoryCodes.length === 0) return '';

    // Find longest common prefix
    const sortedCodes = categoryCodes.sort();
    const first = sortedCodes[0];
    const last = sortedCodes[sortedCodes.length - 1];
    let i = 0;
    while (i < first.length && first.charAt(i) === last.charAt(i)) {
      i++;
    }
    return first.substring(0, i);
  };

  const loadAccountCodes = async () => {
    setLoading(true);
    try {
      const codes = await getAccountCodes();
      setAccountCodes(codes);
    } catch (error) {
      console.error('Failed to load account codes', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAccountCodes();
  }, []);

  const handleOpen = () => {
    setFormData({
      mainCategory: '',
      subCategory: '',
      code: ''
    });
    setIsEditing(false);
    setOpen(true);
  };

  const handleEdit = (code: AccountCode) => {
    setFormData({
      mainCategory: code.mainCategory,
      subCategory: code.subCategory,
      code: code.code
    });
    setCurrentId(code.id);
    setIsEditing(true);
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  const confirmDelete = (id: number) => {
    setItemToDelete(id);
    setDeleteDialogOpen(true);
  };

  const handleDelete = async () => {
    if (itemToDelete === null) return;
    
    setLoading(true);
    try {
      await deleteAccountCode(itemToDelete);
      await loadAccountCodes();
    } catch (error) {
      console.error('Failed to delete', error);
    } finally {
      setLoading(false);
      setItemToDelete(null);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    
    try {
      // If editing, use current ID. If adding, generate new ID.
      // NOTE: In a real app with GAS, the ID should probably be generated by the server or UUID.
      // For now, client-side max ID + 1 is risky for concurrency but okay for this prototype.
      const id = isEditing && currentId !== null 
        ? currentId 
        : (accountCodes.length > 0 ? Math.max(...accountCodes.map(item => item.id)) + 1 : 1);
        
      const codeToSave: AccountCode = {
        id,
        ...formData
      };
      
      await saveAccountCode(codeToSave);
      await loadAccountCodes();
      handleClose();
    } catch (error) {
      console.error('Error saving account code:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box>
      <Backdrop open={loading} sx={{ color: '#fff', zIndex: (theme) => theme.zIndex.drawer + 1 }}>
        <CircularProgress color="inherit" />
      </Backdrop>

      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
        <Typography variant="h4" fontWeight="bold">Account Codes</Typography>
        <Box>
          <IconButton onClick={loadAccountCodes} disabled={loading} sx={{ mr: 1 }}>
            <Refresh />
          </IconButton>
          <Button variant="contained" startIcon={<Add />} onClick={handleOpen}>
            Add Account Code
          </Button>
        </Box>
      </Box>

      <Paper sx={{ width: '100%', overflow: 'hidden' }}>
        <TableContainer>
          <Table stickyHeader>
            <TableHead>
              <TableRow>
                <TableCell sx={{ fontWeight: 'bold' }}>ID</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Sub Category</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Main Category</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Account Code</TableCell>
                <TableCell align="right" sx={{ fontWeight: 'bold' }}>Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {accountCodes.map((row) => (
                <TableRow key={row.id} hover>
                  <TableCell>#{row.id}</TableCell>
                  <TableCell>{row.subCategory}</TableCell>
                  <TableCell>
                    <Chip 
                      label={row.mainCategory} 
                      size="small" 
                      color={
                        row.mainCategory === 'General Fund' ? 'primary' :
                        row.mainCategory === 'Special Education Fund' ? 'secondary' : 'default'
                      }
                      variant="outlined"
                    />
                  </TableCell>
                  <TableCell sx={{ fontFamily: 'monospace', fontWeight: 'medium' }}>{row.code}</TableCell>
                  <TableCell align="right">
                    <IconButton size="small" color="primary" onClick={() => handleEdit(row)}>
                      <Edit fontSize="small" />
                    </IconButton>
                    <IconButton size="small" color="error" onClick={() => confirmDelete(row.id)}>
                      <Delete fontSize="small" />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))}
              {accountCodes.length === 0 && !loading && (
                <TableRow>
                  <TableCell colSpan={5} align="center" sx={{ py: 3 }}>
                    <Typography color="text.secondary">No account codes found.</Typography>
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>

      {/* Add/Edit Dialog */}
      <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
        <form onSubmit={handleSubmit}>
          <DialogTitle>{isEditing ? 'Edit Account Code' : 'Add Account Code'}</DialogTitle>
          <DialogContent>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid size={{ xs: 12 }}>
                <TextField
                  fullWidth
                  label="Sub Category"
                  value={formData.subCategory}
                  onChange={(e) => setFormData({ ...formData, subCategory: e.target.value })}
                  placeholder="e.g. Tax Revenue"
                  required
                />
              </Grid>
              <Grid size={{ xs: 12 }}>
                <Autocomplete
                  freeSolo
                  options={uniqueMainCategories}
                  value={formData.mainCategory}
                   onChange={(_, newValue) => {
                    const category = newValue || '';
                    const prefix = getCommonPrefix(category, accountCodes);
                    setFormData({ 
                      ...formData, 
                      mainCategory: category,
                      code: prefix // Autofill code with prefix
                    });
                  }}
                   onInputChange={(_, newInputValue) => {
                    setFormData({ ...formData, mainCategory: newInputValue });
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      fullWidth
                      label="Main Category"
                      placeholder="e.g. General Fund"
                      required
                    />
                  )}
                />
              </Grid>
              <Grid size={{ xs: 12 }}>
                <TextField
                  fullWidth
                  label="Account Code"
                  value={formData.code}
                  onChange={(e) => setFormData({ ...formData, code: e.target.value })}
                  placeholder="e.g. 1-01-01-010"
                  required
                />
              </Grid>
            </Grid>
          </DialogContent>
          <DialogActions sx={{ p: 3 }}>
            <Button onClick={handleClose} color="inherit">
              Cancel
            </Button>
            <Button type="submit" variant="contained" disabled={loading}>
              {isEditing ? 'Save Changes' : 'Add Code'}
            </Button>
          </DialogActions>
        </form>
      </Dialog>

      <ConfirmDialog
        open={deleteDialogOpen}
        onClose={() => setDeleteDialogOpen(false)}
        onConfirm={handleDelete}
        title="Delete Account Code"
        message="Are you sure you want to delete this account code? This action cannot be undone."
        confirmText="Delete"
        severity="error"
      />
    </Box>
  );
};
